import { Megaphone, Plus, Send, Users } from 'lucide-react'
import { type FormEvent, useEffect, useState } from 'react'
import { createChannel, getChannelPosts, getChannels, joinChannel, postToChannel } from '../api/social'
import { useAuth } from '../context/AuthContext'
import type { Channel, ChannelPost } from '../lib/types'
import { relativeTime } from '../lib/time'
import EmptyState from '../components/EmptyState'

export default function Channels(){const{user}=useAuth();const[channels,setChannels]=useState<Channel[]>([]);const[selected,setSelected]=useState('');const[posts,setPosts]=useState<ChannelPost[]>([]);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[body,setBody]=useState('');const[creating,setCreating]=useState(false);const[status,setStatus]=useState('')
  const load=async()=>{try{const list=await getChannels();setChannels(list);if(!selected&&list[0])setSelected(list[0].id)}catch(e){setStatus(e instanceof Error?e.message:'Falha ao carregar canais.')}}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(!selected){setPosts([]);return}void getChannelPosts(selected).then(setPosts).catch(e=>setStatus(e instanceof Error?e.message:'Falha ao carregar canal.'))},[selected])
  const selectedChannel=channels.find(c=>c.id===selected)
  const create=async(e:FormEvent)=>{e.preventDefault();try{const id=await createChannel(title,description);setTitle('');setDescription('');setCreating(false);await load();setSelected(id)}catch(err){setStatus(err instanceof Error?err.message:'Falha ao criar canal.')}}
  const join=async()=>{if(!selectedChannel)return;try{const joined=await joinChannel(selectedChannel.id,Boolean(selectedChannel.joined));setChannels(items=>items.map(c=>c.id===selectedChannel.id?{...c,joined,memberCount:Math.max(0,(c.memberCount??0)+(joined?1:-1))}:c))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao entrar no canal.')}}
  const send=async(e:FormEvent)=>{e.preventDefault();if(!selected||!body.trim())return;try{await postToChannel(selected,body);setBody('');setPosts(await getChannelPosts(selected))}catch(err){setStatus(err instanceof Error?err.message:'Falha ao publicar no canal.')}}
  return <div className="page channels-page"><header className="page-header"><div><span className="eyebrow">Comunidades</span><h1>Canais</h1></div><button className="btn primary" onClick={()=>setCreating(v=>!v)}><Plus size={16}/> Criar canal</button></header>{creating&&<form className="channel-create" onSubmit={create}><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} placeholder="Nome do canal" required/><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} placeholder="Sobre o que é este canal?"/><button className="btn primary">Criar</button></form>}{status&&<div className="form-status error">{status}</div>}<div className="channels-layout"><aside className="channel-list">{channels.map(channel=><button key={channel.id} className={selected===channel.id?'active':''} onClick={()=>setSelected(channel.id)}><span><Megaphone size={18}/></span><div><strong>{channel.title}</strong><small><Users size={12}/>{channel.memberCount??0}</small></div></button>)}</aside><section className="channel-pane">{selectedChannel?<><header><div><strong>{selectedChannel.title}</strong><p>{selectedChannel.description}</p></div>{selectedChannel.ownerId!==user?.uid&&<button className="btn ghost" onClick={()=>void join()}>{selectedChannel.joined?'Sair':'Participar'}</button>}</header><div className="channel-posts">{posts.length?posts.map(post=><article key={post.id}><p>{post.body}</p><small>{relativeTime(post.createdAt)}</small></article>):<EmptyState icon={<Megaphone/>} title="Ainda não há atualizações."/>}</div>{selectedChannel.ownerId===user?.uid&&<form className="message-form channel-form" onSubmit={send}><input value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder="Publicar atualização…"/><button disabled={!body.trim()}><Send size={18}/></button></form>}</>:<EmptyState icon={<Megaphone/>} title="Nenhum canal ainda."/>}</section></div></div>}
