import { Check, Loader2, MessageSquarePlus, Sparkles, UserRoundPlus, X } from 'lucide-react'
import { type FormEvent, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { addPromptEntry, createPrompt, getCollaborationInvites, getPrompts, respondCollaboration, type CollaborationInvite, type PromptItem } from '../api/advanced'
import { createThread } from '../api/threads'
import { getProfile } from '../api/users'
import { useAuth } from '../context/AuthContext'

export default function CreatorTools(){
  const{user}=useAuth();const[collabs,setCollabs]=useState<Array<CollaborationInvite&{otherName:string;otherUsername:string}>>([]);const[prompts,setPrompts]=useState<PromptItem[]>([]);const[newPrompt,setNewPrompt]=useState('');const[responses,setResponses]=useState<Record<string,string>>({});const[busy,setBusy]=useState('');const[status,setStatus]=useState('')
  const load=async()=>{try{const[invites,promptRows]=await Promise.all([getCollaborationInvites(),getPrompts()]);const hydrated=await Promise.all(invites.map(async invite=>{const otherId=invite.ownerId===user?.uid?invite.collaboratorId:invite.ownerId;const profile=await getProfile(otherId);return{...invite,otherName:profile?.displayName??'Threader',otherUsername:profile?.username??'threader'}}));setCollabs(hydrated);setPrompts(promptRows)}catch(e){setStatus(e instanceof Error?e.message:'Falha ao carregar ferramentas.')}}
  useEffect(()=>{void load()},[user?.uid])
  const answer=async(invite:CollaborationInvite,accept:boolean)=>{setBusy(invite.id);try{await respondCollaboration(invite.id,accept);await load()}catch(e){setStatus(e instanceof Error?e.message:'Falha ao responder Collab.')}finally{setBusy('')}}
  const submitPrompt=async(e:FormEvent)=>{e.preventDefault();if(!newPrompt.trim())return;setBusy('prompt');try{await createPrompt(newPrompt);setNewPrompt('');await load()}catch(err){setStatus(err instanceof Error?err.message:'Falha ao criar prompt.')}finally{setBusy('')}}
  const participate=async(prompt:PromptItem)=>{const text=(responses[prompt.id]??'').trim();if(!text||!user)return;setBusy(`entry:${prompt.id}`);try{const threadId=await createThread(user.uid,text);await addPromptEntry(prompt.id,'thread',threadId);setResponses(current=>({...current,[prompt.id]:''}));setStatus('Sua resposta foi publicada como Thread e ligada a este “Sua vez”.');await load();window.dispatchEvent(new Event('threadly:refresh'))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao participar.')}finally{setBusy('')}}
  return <div className="page narrow-page creator-tools-page"><header className="page-header"><div><span className="eyebrow">Criação social</span><h1>Ferramentas</h1></div><Sparkles/></header>{status&&<div className="form-status success">{status}</div>}
    <section className="settings-section"><div className="settings-section-title"><div><UserRoundPlus size={18}/><h2>Collabs</h2></div><span>{collabs.filter(c=>c.status==='pending').length} pendente(s)</span></div><p className="account-helper">Convites feitos no compositor aparecem aqui. Quando aceitos, a publicação é marcada como Collab.</p><div className="collab-list">{collabs.length?collabs.map(invite=>{const incoming=invite.collaboratorId===user?.uid;return <article key={invite.id} className="collab-row"><div><strong>@{invite.otherUsername}</strong><small>{invite.targetType==='thread'?'Thread':'Clip'} · {invite.status==='pending'?'Pendente':invite.status==='accepted'?'Aceita':'Recusada'}</small></div><Link to={invite.targetType==='thread'?`/post/${invite.targetId}`:`/watch/${invite.targetId}`} className="text-btn">Ver publicação</Link>{incoming&&invite.status==='pending'&&<><button className="icon-btn approve" disabled={busy===invite.id} onClick={()=>void answer(invite,true)} title="Aceitar"><Check size={16}/></button><button className="icon-btn" disabled={busy===invite.id} onClick={()=>void answer(invite,false)} title="Recusar"><X size={16}/></button></>}</article>}):<div className="empty-mini">Nenhuma Collab ainda.</div>}</div></section>
    <section className="settings-section"><div className="settings-section-title"><div><MessageSquarePlus size={18}/><h2>Sua vez</h2></div><span>Add Yours</span></div><form className="prompt-create" onSubmit={submitPrompt}><input value={newPrompt} onChange={e=>setNewPrompt(e.target.value)} maxLength={160} placeholder="Ex.: Mostre uma foto do seu lugar favorito"/><button className="btn primary" disabled={busy==='prompt'||!newPrompt.trim()}>{busy==='prompt'?<Loader2 className="spin" size={15}/>:<Sparkles size={15}/>} Criar</button></form><div className="prompt-list">{prompts.map(prompt=><article key={prompt.id} className="prompt-card"><strong>{prompt.body}</strong><small>{prompt.entries} {prompt.entries===1?'participação':'participações'}</small><div><input value={responses[prompt.id]??''} onChange={e=>setResponses(current=>({...current,[prompt.id]:e.target.value}))} maxLength={800} placeholder="Responda com uma Thread…"/><button className="btn ghost" disabled={busy===`entry:${prompt.id}`||!(responses[prompt.id]??'').trim()} onClick={()=>void participate(prompt)}>{busy===`entry:${prompt.id}`?<Loader2 className="spin" size={14}/>:<MessageSquarePlus size={14}/>} Participar</button></div></article>)}</div></section>
    <section className="settings-section"><h2>Destaques e perfil</h2><p className="account-helper">Crie Destaques diretamente no seu perfil usando o arquivo privado de Stories. Publicações próprias também podem ser fixadas pelo menu ⋯.</p><Link className="btn ghost account-action" to="/profile">Abrir meu perfil</Link></section>
  </div>
}
