import { Loader2, Save } from 'lucide-react'
import { type FormEvent, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Avatar from '../components/Avatar'
import { getProfile, updateProfile } from '../api/users'
import { useAuth } from '../context/AuthContext'
import type { Profile } from '../lib/types'

export default function EditProfile(){const{user}=useAuth();const navigate=useNavigate();const[profile,setProfile]=useState<Profile|null>(null);const[name,setName]=useState('');const[username,setUsername]=useState('');const[bio,setBio]=useState('');const[website,setWebsite]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');useEffect(()=>{void getProfile(user?.uid).then(p=>{setProfile(p);if(p){setName(p.displayName);setUsername(p.username);setBio(p.bio);setWebsite(p.website??'')}})},[user?.uid]);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setStatus('');try{await updateProfile({displayName:name,username,bio,website});navigate('/profile')}catch(error){setStatus(error instanceof Error?error.message:'Falha ao salvar.')}finally{setBusy(false)}};return <div className="page narrow-page"><header className="page-header"><div><span className="eyebrow">Perfil</span><h1>Editar perfil</h1></div></header><form className="settings-form" onSubmit={submit}><div className="edit-avatar"><Avatar name={name||'Você'} src={profile?.avatarUrl} size="lg"/><div><strong>Foto de perfil</strong><p>A foto vem do Firebase/Google nesta versão.</p></div></div><label className="stack-field"><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></label><label className="stack-field"><span>@usuário</span><input value={username} onChange={e=>setUsername(e.target.value)} maxLength={24} required/></label><label className="stack-field"><span>Bio</span><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={240}/></label><label className="stack-field"><span>Site</span><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..."/></label>{status&&<div className="form-status error">{status}</div>}<div className="dialog-actions"><button type="button" className="btn ghost" onClick={()=>navigate(-1)}>Cancelar</button><button className="btn primary" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:<Save size={17}/>} Salvar</button></div></form></div>}
