import { Check, Lock, ShieldCheck, UserCheck, UserX, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getFollowRequests, respondFollowRequest, updatePrivacySettings } from '../api/social'
import { getProfile } from '../api/users'
import type { FollowRequestItem, Profile } from '../lib/types'
import Avatar from '../components/Avatar'

export default function Privacy(){
  const[profile,setProfile]=useState<Profile|null>(null);const[requests,setRequests]=useState<FollowRequestItem[]>([]);const[busy,setBusy]=useState(false);const[status,setStatus]=useState('')
  const load=async()=>{try{const[p,r]=await Promise.all([getProfile(),getFollowRequests()]);setProfile(p);setRequests(r)}catch(e){setStatus(e instanceof Error?e.message:'Falha ao carregar privacidade.')}}
  useEffect(()=>{void load()},[])
  const save=async()=>{if(!profile)return;setBusy(true);setStatus('');try{await updatePrivacySettings({isPrivate:Boolean(profile.isPrivate),allowMessagesFrom:profile.allowMessagesFrom??'everyone',allowMentionsFrom:profile.allowMentionsFrom??'everyone',allowCommentsFrom:profile.allowCommentsFrom??'everyone',showActivityStatus:profile.showActivityStatus!==false});setStatus('Configurações de privacidade salvas.')}catch(e){setStatus(e instanceof Error?e.message:'Falha ao salvar.')}finally{setBusy(false)}}
  const answer=async(id:string,accept:boolean)=>{try{await respondFollowRequest(id,accept);setRequests(items=>items.filter(item=>item.requesterId!==id))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao responder solicitação.')}}
  if(!profile)return <div className="page"><div className="center-status">Carregando privacidade…</div></div>
  const set=<K extends keyof Profile,>(key:K,value:Profile[K])=>setProfile(p=>p?{...p,[key]:value}:p)
  return <div className="page narrow-page"><header className="page-header"><div><span className="eyebrow">Quem entra no seu espaço</span><h1>Privacidade</h1></div><ShieldCheck/></header>{status&&<div className="form-status success">{status}</div>}
    <section className="settings-section"><div className="settings-section-title"><div><Lock size={18}/><h2>Visibilidade</h2></div></div><label className="privacy-switch"><span><strong>Conta privada</strong><small>Novos seguidores precisam da sua aprovação. Quem não segue você não vê suas publicações protegidas.</small></span><input type="checkbox" checked={Boolean(profile.isPrivate)} onChange={e=>set('isPrivate',e.target.checked)}/></label><label className="privacy-switch"><span><strong>Status de atividade</strong><small>Permite mostrar quando você está online nas conversas.</small></span><input type="checkbox" checked={profile.showActivityStatus!==false} onChange={e=>set('showActivityStatus',e.target.checked)}/></label></section>
    <section className="settings-section privacy-selects"><h2>Interações</h2><label><span>Quem pode enviar mensagens</span><select value={profile.allowMessagesFrom??'everyone'} onChange={e=>set('allowMessagesFrom',e.target.value as Profile['allowMessagesFrom'])}><option value="everyone">Todos (outros vão para solicitações)</option><option value="following">Somente quem eu sigo</option><option value="none">Ninguém</option></select></label><label><span>Quem pode mencionar você</span><select value={profile.allowMentionsFrom??'everyone'} onChange={e=>set('allowMentionsFrom',e.target.value as Profile['allowMentionsFrom'])}><option value="everyone">Todos</option><option value="following">Quem eu sigo</option><option value="none">Ninguém</option></select></label><label><span>Quem pode comentar</span><select value={profile.allowCommentsFrom??'everyone'} onChange={e=>set('allowCommentsFrom',e.target.value as Profile['allowCommentsFrom'])}><option value="everyone">Todos</option><option value="following">Quem eu sigo</option><option value="none">Ninguém</option></select></label><button className="btn primary" disabled={busy} onClick={()=>void save()}><Check size={16}/>{busy?'Salvando…':'Salvar privacidade'}</button></section>
    <section className="settings-section"><div className="settings-section-title"><div><UserCheck size={18}/><h2>Solicitações para seguir</h2></div><span>{requests.length}</span></div>{requests.length?requests.map(request=><article className="follow-request" key={request.requesterId}><Avatar name={request.displayName} src={request.avatarUrl}/><div><strong>{request.displayName}</strong><small>@{request.username}</small></div><button className="icon-btn approve" onClick={()=>void answer(request.requesterId,true)} title="Aceitar"><Check/></button><button className="icon-btn" onClick={()=>void answer(request.requesterId,false)} title="Recusar"><X/></button></article>):<div className="security-note"><UserX/><p>Nenhuma solicitação pendente.</p></div>}</section>
  </div>
}
