import type { Comment, MediaEditState, NotificationItem, Profile, ThreadPost, ThreadReply, VideoPost } from '../lib/types'

export const mapProfile = (row: Record<string, unknown>): Profile => ({
  id: String(row.id),
  username: String(row.username ?? 'threader'),
  displayName: String(row.display_name ?? row.username ?? 'Threader'),
  bio: String(row.bio ?? ''),
  avatarUrl: row.avatar_url ? String(row.avatar_url) : null,
  website: row.website ? String(row.website) : null,
  followers: Number(row.followers_count ?? 0),
  following: Number(row.following_count ?? 0),
  createdAt: row.created_at ? String(row.created_at) : undefined,
  isPrivate: Boolean(row.is_private),
  allowMessagesFrom: (String(row.allow_messages_from ?? 'everyone') as Profile['allowMessagesFrom']),
  allowMentionsFrom: (String(row.allow_mentions_from ?? 'everyone') as Profile['allowMentionsFrom']),
  allowCommentsFrom: (String(row.allow_comments_from ?? 'everyone') as Profile['allowCommentsFrom']),
  showActivityStatus: row.show_activity_status === undefined ? true : Boolean(row.show_activity_status),
})

export const mapThread = (row: Record<string, unknown>): ThreadPost => ({
  id: String(row.id),
  userId: String(row.user_id),
  username: String(row.username ?? 'threader'),
  displayName: String(row.display_name ?? row.username ?? 'Threader'),
  avatarUrl: row.avatar_url ? String(row.avatar_url) : null,
  body: String(row.body ?? ''),
  imageUrl: row.image_url ? String(row.image_url) : null,
  createdAt: String(row.created_at ?? new Date().toISOString()),
  likes: Number(row.likes_count ?? 0),
  replies: Number(row.replies_count ?? 0),
  audience: String(row.audience ?? 'public') as ThreadPost['audience'],
  commentsEnabled: row.comments_enabled === undefined ? true : Boolean(row.comments_enabled),
  commentPolicy: String(row.comment_policy ?? 'everyone') as ThreadPost['commentPolicy'],
  locationName: row.location_name ? String(row.location_name) : null,
  editedAt: row.edited_at ? String(row.edited_at) : null,
})

export const mapThreadReply = (row: Record<string, unknown>): ThreadReply => ({
  id: String(row.id),
  threadId: String(row.thread_id),
  userId: String(row.user_id),
  username: String(row.username ?? 'threader'),
  displayName: String(row.display_name ?? row.username ?? 'Threader'),
  avatarUrl: row.avatar_url ? String(row.avatar_url) : null,
  body: String(row.body ?? ''),
  createdAt: String(row.created_at ?? new Date().toISOString()),
  replyToId: row.reply_to_id ? String(row.reply_to_id) : null,
  editedAt: row.edited_at ? String(row.edited_at) : null,
  pinned: Boolean(row.pinned_at),
  likes: Number(row.likes_count ?? 0),
})

export const mapVideo = (row: Record<string, unknown>): VideoPost => ({
  id: String(row.id),
  userId: String(row.user_id),
  username: String(row.username ?? 'threader'),
  displayName: String(row.display_name ?? row.username ?? 'Threader'),
  avatarUrl: row.avatar_url ? String(row.avatar_url) : null,
  title: String(row.title ?? ''),
  description: String(row.description ?? ''),
  videoUrl: String(row.video_url ?? ''),
  thumbnailUrl: row.thumbnail_url ? String(row.thumbnail_url) : null,
  createdAt: String(row.created_at ?? new Date().toISOString()),
  likes: Number(row.likes_count ?? 0),
  comments: Number(row.comments_count ?? 0),
  views: Number(row.views_count ?? 0),
  audience: String(row.audience ?? 'public') as VideoPost['audience'],
  commentsEnabled: row.comments_enabled === undefined ? true : Boolean(row.comments_enabled),
  commentPolicy: String(row.comment_policy ?? 'everyone') as VideoPost['commentPolicy'],
  locationName: row.location_name ? String(row.location_name) : null,
  editMetadata: row.edit_metadata && typeof row.edit_metadata === 'object' ? row.edit_metadata as MediaEditState : undefined,
  editedAt: row.edited_at ? String(row.edited_at) : null,
})

export const mapComment = (row: Record<string, unknown>): Comment => ({
  id: String(row.id),
  videoId: String(row.video_id),
  userId: String(row.user_id),
  username: String(row.username ?? 'threader'),
  displayName: String(row.display_name ?? row.username ?? 'Threader'),
  avatarUrl: row.avatar_url ? String(row.avatar_url) : null,
  body: String(row.body ?? ''),
  createdAt: String(row.created_at ?? new Date().toISOString()),
  replyToId: row.reply_to_id ? String(row.reply_to_id) : null,
  editedAt: row.edited_at ? String(row.edited_at) : null,
  pinned: Boolean(row.pinned_at),
  likes: Number(row.likes_count ?? 0),
})

export const mapNotification = (row: Record<string, unknown>): NotificationItem => ({
  id: String(row.id),
  type: (String(row.type ?? 'system') as NotificationItem['type']),
  actorId: row.actor_id ? String(row.actor_id) : null,
  actorUsername: row.actor_username ? String(row.actor_username) : null,
  actorDisplayName: row.actor_display_name ? String(row.actor_display_name) : null,
  actorAvatarUrl: row.actor_avatar_url ? String(row.actor_avatar_url) : null,
  text: String(row.text ?? ''),
  targetUrl: row.target_url ? String(row.target_url) : null,
  createdAt: String(row.created_at ?? new Date().toISOString()),
  read: Boolean(row.read_at),
})
