import { Clapperboard, ImagePlus, Loader2, MapPin, MessageSquareText, Pencil, Save, Sparkles, Upload, X } from 'lucide-react'
import { type FormEvent, useEffect, useRef, useState } from 'react'
import { createStory, saveDraft } from '../api/social'
import { createThread } from '../api/threads'
import { publishVideo } from '../api/upload'
import { useAuth } from '../context/AuthContext'
import type { Audience, MediaEditState } from '../lib/types'
import MediaEditor from './MediaEditor'

type Mode='thread'|'clip'|'story'
type EditedFile={file:File;editMetadata?:MediaEditState}

export default function CreateDialog({open,onClose}:{open:boolean;onClose:()=>void}){
  const dialogRef=useRef<HTMLDialogElement>(null)
  const [mode,setMode]=useState<Mode>('thread');const[body,setBody]=useState('');const[threadMedia,setThreadMedia]=useState<EditedFile[]>([]);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[clip,setClip]=useState<EditedFile|null>(null);const[story,setStory]=useState<EditedFile|null>(null);const[audience,setAudience]=useState<Audience>('public');const[commentsEnabled,setCommentsEnabled]=useState(true);const[commentPolicy,setCommentPolicy]=useState<'everyone'|'following'|'none'>('everyone');const[locationName,setLocationName]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const[editing,setEditing]=useState<{kind:'thread'|'clip'|'story';index:number;file:File}|null>(null)
  const {user,supabaseRoleReady}=useAuth()
  useEffect(()=>{const d=dialogRef.current;if(!d)return;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close()},[open])
  useEffect(()=>{if(mode==='story'&&audience==='public')setAudience('followers')},[mode,audience])
  const reset=()=>{setBody('');setThreadMedia([]);setTitle('');setDescription('');setClip(null);setStory(null);setAudience('public');setCommentsEnabled(true);setCommentPolicy('everyone');setLocationName('');setStatus('')}
  const chooseThreadFiles=(files:FileList|null)=>{if(!files)return;const selected=[...files].slice(0,10).map(file=>({file}));setThreadMedia(selected);if(selected[0])setEditing({kind:'thread',index:0,file:selected[0].file})}
  const chooseSingle=(kind:'clip'|'story',file?:File)=>{if(!file)return;if(kind==='clip')setClip({file});else setStory({file});setEditing({kind,index:0,file})}
  const edited=(file:File,editMetadata:MediaEditState)=>{if(!editing)return;if(editing.kind==='thread')setThreadMedia(items=>items.map((item,index)=>index===editing.index?{file,editMetadata}:item));if(editing.kind==='clip')setClip({file,editMetadata});if(editing.kind==='story')setStory({file,editMetadata});setEditing(null)}
  const saveCurrentDraft=async()=>{try{const payload=mode==='thread'?{body,audience,commentsEnabled,commentPolicy,locationName,mediaNames:threadMedia.map(m=>m.file.name)}:mode==='clip'?{title,description,audience,commentsEnabled,commentPolicy,locationName,fileName:clip?.file.name}:{body,audience,fileName:story?.file.name};await saveDraft(mode,payload);setStatus('Rascunho salvo na sua conta. Arquivos locais precisam ser escolhidos novamente por segurança.')}catch(e){setStatus(e instanceof Error?e.message:'Falha ao salvar rascunho.')}}
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!user){setStatus('Sua sessão expirou. Entre novamente para publicar.');return}if(!supabaseRoleReady){setStatus('Sua sessão ainda não está pronta. Tente novamente em instantes.');return}
    setBusy(true);setStatus(mode==='clip'?'Preparando upload…':'Publicando…')
    try{
      if(mode==='thread'){if(!body.trim()&&!threadMedia.length)throw new Error('Escreva alguma coisa ou adicione mídia.');await createThread(user.uid,body.trim()||' ',threadMedia,{audience,commentsEnabled,commentPolicy:commentsEnabled?commentPolicy:'none',locationName})}
      if(mode==='clip'){if(!clip)throw new Error('Escolha um vídeo.');if(!title.trim())throw new Error('Dê um título ao clip.');await publishVideo({userId:user.uid,file:clip.file,title:title.trim(),description:description.trim(),audience,commentsEnabled,commentPolicy:commentsEnabled?commentPolicy:'none',locationName,editMetadata:clip.editMetadata,onProgress:setStatus})}
      if(mode==='story'){if(!story)throw new Error('Escolha uma foto ou vídeo para o story.');await createStory(story.file,body,audience,story.editMetadata)}
      reset();onClose();window.dispatchEvent(new Event('threadly:refresh'))
    }catch(error){setStatus(error instanceof Error?error.message:'Falha ao publicar.')}finally{setBusy(false)}}
  const activeFile=mode==='clip'?clip:mode==='story'?story:null
  return <><dialog ref={dialogRef} className="create-dialog create-dialog-v4" onClose={onClose}><form onSubmit={submit}><div className="dialog-head"><div><small>Nova publicação</small><h2>Crie no Threadly.</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={21}/></button></div><div className="mode-switch three"><button type="button" className={mode==='thread'?'active':''} onClick={()=>setMode('thread')}><MessageSquareText size={18}/> Thread</button><button type="button" className={mode==='clip'?'active':''} onClick={()=>setMode('clip')}><Clapperboard size={18}/> Clip</button><button type="button" className={mode==='story'?'active':''} onClick={()=>setMode('story')}><Sparkles size={18}/> Story</button></div>
      {mode==='thread'&&<><div className="composer"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={800} placeholder="No que você está pensando?" autoFocus/><div className="composer-foot"><label className="inline-upload"><ImagePlus size={17}/><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" onChange={e=>chooseThreadFiles(e.target.files)}/><span>{threadMedia.length?`${threadMedia.length} mídia(s)`:'Adicionar carrossel'}</span></label><b>{body.length}/800</b></div></div>{threadMedia.length>0&&<div className="composer-media-list">{threadMedia.map((item,index)=><div key={`${item.file.name}-${index}`}><span>{index+1}</span><strong>{item.file.name}</strong><button type="button" onClick={()=>setEditing({kind:'thread',index,file:item.file})}><Pencil size={14}/> Editar</button><button type="button" onClick={()=>setThreadMedia(items=>items.filter((_,i)=>i!==index))}><X size={14}/></button></div>)}</div>}</>}
      {mode==='clip'&&<div className="clip-form"><label className={`dropzone ${clip?'has-file':''}`}><input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>chooseSingle('clip',e.target.files?.[0])}/><Upload size={28}/><strong>{clip?clip.file.name:'Escolha um vídeo'}</strong><span>MP4, WebM ou MOV · até 200 MB.</span></label>{clip&&<button type="button" className="btn editor-launch" onClick={()=>setEditing({kind:'clip',index:0,file:clip.file})}><Pencil size={16}/> Abrir editor</button>}<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="Título"/><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} placeholder="Descrição (opcional)"/></div>}
      {mode==='story'&&<div className="clip-form"><label className={`dropzone ${story?'has-file':''}`}><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" onChange={e=>chooseSingle('story',e.target.files?.[0])}/><Sparkles size={28}/><strong>{story?story.file.name:'Escolha foto ou vídeo'}</strong><span>O story expira em 24 horas.</span></label>{story&&<button type="button" className="btn editor-launch" onClick={()=>setEditing({kind:'story',index:0,file:story.file})}><Pencil size={16}/> Abrir editor</button>}<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder="Legenda (opcional)"/></div>}
      <div className="publish-settings"><label><span>Quem pode ver</span><select value={audience} onChange={e=>setAudience(e.target.value as Audience)}><option value="public">Público</option><option value="followers">Seguidores</option><option value="close_friends">Amigos próximos</option></select></label>{mode!=='story'&&<><label className="setting-toggle"><input type="checkbox" checked={commentsEnabled} onChange={e=>setCommentsEnabled(e.target.checked)}/><span>Permitir comentários</span></label>{commentsEnabled&&<label><span>Comentários de</span><select value={commentPolicy} onChange={e=>setCommentPolicy(e.target.value as typeof commentPolicy)}><option value="everyone">Todos</option><option value="following">Quem sigo</option><option value="none">Ninguém</option></select></label>}<label><span><MapPin size={14}/> Local (opcional)</span><input value={locationName} maxLength={120} onChange={e=>setLocationName(e.target.value)} placeholder="Adicionar localização"/></label></>}</div>
      {status&&<div className={`form-status ${/falha|expirou|erro/i.test(status)?'error':''}`}>{status}</div>}<div className="dialog-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>void saveCurrentDraft()}><Save size={16}/> Rascunho</button><button type="button" className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={busy}>{busy&&<Loader2 className="spin" size={17}/>} Publicar</button></div></form></dialog><MediaEditor file={editing?.file??null} onCancel={()=>setEditing(null)} onApply={edited}/></>
}
