import { Loader2, Plus, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { createHighlightFromArchive, deleteHighlight, getHighlights, getStoryArchive, type Highlight } from '../api/advanced'
import type { Story } from '../lib/types'

export default function HighlightsRail({userId,own=false}:{userId:string;own?:boolean}){
  const[highlights,setHighlights]=useState<Highlight[]>([]);const[archive,setArchive]=useState<Story[]>([]);const[managerOpen,setManagerOpen]=useState(false);const[active,setActive]=useState<{highlight:number;item:number}|null>(null);const[title,setTitle]=useState('');const[selected,setSelected]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const viewRef=useRef<HTMLDialogElement>(null);const manageRef=useRef<HTMLDialogElement>(null)
  const load=async()=>{try{setHighlights(await getHighlights(userId))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao carregar Destaques.')}}
  useEffect(()=>{void load()},[userId])
  useEffect(()=>{const d=viewRef.current;if(active&&!d?.open)d?.showModal();if(!active&&d?.open)d.close()},[active])
  useEffect(()=>{const d=manageRef.current;if(managerOpen&&!d?.open)d?.showModal();if(!managerOpen&&d?.open)d.close()},[managerOpen])
  const openManager=async()=>{setManagerOpen(true);setStatus('');try{setArchive(await getStoryArchive())}catch(e){setStatus(e instanceof Error?e.message:'Falha ao abrir seu arquivo de Stories.')}}
  const create=async()=>{if(!title.trim()||!selected.length)return;setBusy(true);setStatus('');try{await createHighlightFromArchive(title,selected);setTitle('');setSelected([]);setManagerOpen(false);await load()}catch(e){setStatus(e instanceof Error?e.message:'Falha ao criar Destaque.')}finally{setBusy(false)}}
  const remove=async(id:string)=>{if(!window.confirm('Excluir este Destaque? Os Stories continuarão no seu arquivo.'))return;try{await deleteHighlight(id);setHighlights(items=>items.filter(item=>item.id!==id))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao excluir Destaque.')}}
  const current=active?highlights[active.highlight]?.items[active.item]:null
  if(!highlights.length&&!own)return null
  return <><section className="highlights-rail" aria-label="Destaques">{own&&<button className="highlight-entry highlight-new" onClick={()=>void openManager()}><span><Plus/></span><small>Novo</small></button>}{highlights.map((highlight,index)=><div className="highlight-wrap" key={highlight.id}><button className="highlight-entry" onClick={()=>highlight.items.length&&setActive({highlight:index,item:0})}><span>{highlight.items[0]?.mediaType==='video'?<video src={highlight.items[0].mediaUrl} muted playsInline/>:highlight.items[0]?<img src={highlight.items[0].mediaUrl} alt=""/>:<Plus/>}</span><small>{highlight.title}</small></button>{own&&<button className="highlight-remove" onClick={()=>void remove(highlight.id)} title="Excluir Destaque"><Trash2 size={12}/></button>}</div>)}</section>{status&&<small className="inline-status">{status}</small>}
    <dialog ref={viewRef} className="highlight-viewer" onClose={()=>setActive(null)}>{current&&active&&<div className="highlight-stage"><header><strong>{highlights[active.highlight].title}</strong><button className="icon-btn" onClick={()=>setActive(null)}><X/></button></header>{current.mediaType==='video'?<video src={current.mediaUrl} autoPlay controls playsInline/>:<img src={current.mediaUrl} alt="Destaque"/>}<p>{current.caption}</p><nav>{highlights[active.highlight].items.map((item,index)=><button key={item.storyId} className={index===active.item?'active':''} onClick={()=>setActive({...active,item:index})}/>)}</nav></div>}</dialog>
    <dialog ref={manageRef} className="highlight-manager" onClose={()=>setManagerOpen(false)}><header><div><span className="eyebrow">Arquivo privado</span><h2>Novo Destaque</h2></div><button className="icon-btn" onClick={()=>setManagerOpen(false)}><X/></button></header><label className="stack-field"><span>Nome</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={40} placeholder="Ex.: Viagens"/></label><div className="archive-grid">{archive.length?archive.map(story=><button key={story.id} className={selected.includes(story.id)?'selected':''} onClick={()=>setSelected(ids=>ids.includes(story.id)?ids.filter(id=>id!==story.id):[...ids,story.id])}>{story.mediaType==='video'?<video src={story.mediaUrl} muted playsInline/>:<img src={story.mediaUrl} alt=""/>}<i>{selected.includes(story.id)?'✓':''}</i></button>):<div className="empty-mini">Seu arquivo de Stories ainda está vazio.</div>}</div>{status&&<div className="form-status error">{status}</div>}<footer><button className="btn ghost" onClick={()=>setManagerOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy||!title.trim()||!selected.length} onClick={()=>void create()}>{busy&&<Loader2 className="spin" size={15}/>} Criar Destaque</button></footer></dialog>
  </>
}
