import { Check, Link2, Loader2, Send, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { getConversations, sendMessage } from '../api/messages'
import type { ConversationSummary } from '../lib/types'
import Avatar from './Avatar'

export default function ShareToMessagesDialog({open,onClose,targetType,targetId,title,url}:{open:boolean;onClose:()=>void;targetType:'thread'|'video'|'profile';targetId:string;title:string;url:string}){
  const ref=useRef<HTMLDialogElement>(null);const[conversations,setConversations]=useState<ConversationSummary[]>([]);const[selected,setSelected]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[busy,setBusy]=useState(false);const[status,setStatus]=useState('')
  useEffect(()=>{const d=ref.current;if(!d)return;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close();if(open){setLoading(true);setStatus('');setSelected([]);void getConversations().then(items=>setConversations(items.filter(c=>c.requestState!=='requested'))).catch(e=>setStatus(e instanceof Error?e.message:'Falha ao carregar conversas.')).finally(()=>setLoading(false))}},[open])
  const toggle=(id:string)=>setSelected(ids=>ids.includes(id)?ids.filter(item=>item!==id):[...ids,id])
  const send=async()=>{if(!selected.length)return;setBusy(true);setStatus('');try{await Promise.all(selected.map(conversationId=>sendMessage(conversationId,'',{sharedType:targetType,sharedId:targetId})));setStatus('Enviado.');window.setTimeout(onClose,450)}catch(e){setStatus(e instanceof Error?e.message:'Falha ao enviar.')}finally{setBusy(false)}}
  const copy=async()=>{try{await navigator.clipboard.writeText(url);setStatus('Link copiado.')}catch{setStatus('Não foi possível copiar o link.')}}
  return <dialog ref={ref} className="sheet-dialog share-dialog" onClose={onClose}><div className="sheet-head"><div><span className="eyebrow">Enviar no Threadly</span><h2>{title}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><button className="share-copy" onClick={()=>void copy()}><Link2 size={16}/><span>Copiar link</span></button><div className="share-conversations">{loading?<div className="center-status"><Loader2 className="spin"/> carregando</div>:conversations.map(c=>{const checked=selected.includes(c.id);return <button key={c.id} className={checked?'selected':''} onClick={()=>toggle(c.id)}><Avatar name={c.kind==='group'?(c.title||'Grupo'):c.participantName} src={c.participantAvatarUrl}/><div><strong>{c.kind==='group'?(c.title||'Grupo'):c.participantName}</strong><small>{c.kind==='group'?'Grupo':`@${c.participantUsername}`}</small></div><span>{checked?<Check size={15}/>:<Send size={14}/>}</span></button>})}</div>{status&&<div className="form-status success">{status}</div>}<footer><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={busy||!selected.length} onClick={()=>void send()}>{busy?<Loader2 className="spin" size={15}/>:<Send size={15}/>} Enviar {selected.length?`(${selected.length})`:''}</button></footer></dialog>
}
