import { Bookmark, ChevronLeft, ChevronRight, Flag, FolderPlus, Heart, Link2, MapPin, MessageCircle, MoreHorizontal, Repeat2 } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toggleThreadBookmark } from '../api/bookmarks'
import { toggleThreadLike } from '../api/likes'
import { toggleRepost } from '../api/social'
import type { ThreadPost } from '../lib/types'
import { relativeTime } from '../lib/time'
import Avatar from './Avatar'
import CollectionPicker from './CollectionPicker'
import ReportDialog from './ReportDialog'

export default function ThreadCard({ post }: { post: ThreadPost }) {
  const navigate = useNavigate();const[liked,setLiked]=useState(Boolean(post.liked));const[saved,setSaved]=useState(Boolean(post.saved));const[reposted,setReposted]=useState(Boolean(post.reposted));const[reportOpen,setReportOpen]=useState(false);const[collectionOpen,setCollectionOpen]=useState(false);const[menuOpen,setMenuOpen]=useState(false);const[status,setStatus]=useState('');const[slide,setSlide]=useState(0)
  const likeCount = post.likes + (liked && !post.liked ? 1 : 0) - (!liked && post.liked ? 1 : 0)
  const media=post.media?.length?post.media:post.imageUrl?[{id:'legacy',type:'image' as const,url:post.imageUrl,position:0}]:[]
  const doLike=async()=>{const p=liked;setLiked(!p);try{setLiked(await toggleThreadLike(post.id,p))}catch(error){setLiked(p);setStatus(error instanceof Error?error.message:'Falha ao curtir.')}}
  const doSave=async()=>{const p=saved;setSaved(!p);try{const next=await toggleThreadBookmark(post.id,p);setSaved(next);if(next)setCollectionOpen(true)}catch(error){setSaved(p);setStatus(error instanceof Error?error.message:'Falha ao salvar.')}}
  const doRepost=async()=>{const p=reposted;setReposted(!p);try{setReposted(await toggleRepost('thread',post.id,p))}catch(error){setReposted(p);setStatus(error instanceof Error?error.message:'Falha ao repostar.')}}
  const share=async()=>{const url=`${location.origin}${location.pathname}#/post/${post.id}`;if(navigator.share)await navigator.share({title:`Thread de ${post.displayName}`,text:post.body,url}).catch(()=>undefined);else await navigator.clipboard.writeText(url).then(()=>setStatus('Link copiado.')).catch(()=>undefined)}
  return <article className="thread-card"><button className="avatar-button" onClick={()=>navigate(`/u/${post.username}`)}><Avatar name={post.displayName} src={post.avatarUrl}/></button><div className="thread-main"><header className="post-head"><button className="identity-link" onClick={()=>navigate(`/u/${post.username}`)}><strong>{post.displayName}</strong><span>@{post.username} · {relativeTime(post.createdAt)}{post.editedAt?' · editado':''}</span></button><div className="menu-wrap"><button className="icon-btn quiet" aria-label="Mais opções" onClick={()=>setMenuOpen(v=>!v)}><MoreHorizontal size={19}/></button>{menuOpen&&<div className="mini-menu">{saved&&<button onClick={()=>{setCollectionOpen(true);setMenuOpen(false)}}><FolderPlus size={15}/> Adicionar à coleção</button>}<button onClick={()=>{setReportOpen(true);setMenuOpen(false)}}><Flag size={15}/> Denunciar</button></div>}</div></header><button className="thread-open" onClick={()=>navigate(`/post/${post.id}`)}><p className="thread-body">{post.body}</p></button>{post.locationName&&<span className="post-location"><MapPin size={12}/>{post.locationName}</span>}{media.length>0&&<div className="thread-carousel">{media.map((item,index)=><div key={item.id} className={index===slide?'active':''}>{item.type==='video'?<video src={item.url} controls playsInline preload="metadata"/>:<img src={item.url} alt={item.altText||''} loading="lazy"/>}</div>)}{media.length>1&&<><button className="carousel-prev" onClick={()=>setSlide(i=>(i-1+media.length)%media.length)}><ChevronLeft/></button><button className="carousel-next" onClick={()=>setSlide(i=>(i+1)%media.length)}><ChevronRight/></button><span className="carousel-count">{slide+1}/{media.length}</span></>}</div>}<footer className="post-actions"><button className={liked?'liked':''} onClick={()=>void doLike()}><Heart size={19} fill={liked?'currentColor':'none'}/><span>{likeCount}</span></button><button onClick={()=>navigate(`/post/${post.id}`)}><MessageCircle size={19}/><span>{post.replies}</span></button><button className={reposted?'reposted':''} onClick={()=>void doRepost()}><Repeat2 size={18}/></button><button onClick={()=>void share()} title="Compartilhar"><Link2 size={18}/></button><button className={`push-right ${saved?'saved':''}`} onClick={()=>void doSave()}><Bookmark size={18} fill={saved?'currentColor':'none'}/></button></footer>{status&&<small className="inline-status">{status}</small>}</div><ReportDialog open={reportOpen} onClose={()=>setReportOpen(false)} targetType="thread" targetId={post.id}/><CollectionPicker open={collectionOpen} onClose={()=>setCollectionOpen(false)} targetType="thread" targetId={post.id}/></article>
}
