import { Bookmark, Flag, Heart, MessageCircle, MoreHorizontal, Pin, Repeat2, Share2, Trash2, Volume2, VolumeX } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toggleProfilePin } from '../api/advanced'
import { toggleVideoBookmark } from '../api/bookmarks'
import { deleteVideo } from '../api/content'
import { toggleFollowState } from '../api/follows'
import { toggleVideoLike } from '../api/likes'
import { recordView } from '../api/reels'
import { toggleRepost } from '../api/social'
import { useAuth } from '../context/AuthContext'
import type { FollowState, VideoPost } from '../lib/types'
import { formatCompact } from '../lib/time'
import Avatar from './Avatar'
import CommentsDialog from './CommentsDialog'
import ReportDialog from './ReportDialog'

export default function VideoCard({ video }: { video: VideoPost }) {
  const navigate=useNavigate();const{user}=useAuth();const ref=useRef<HTMLVideoElement>(null);const[muted,setMuted]=useState(true);const[liked,setLiked]=useState(Boolean(video.liked));const[saved,setSaved]=useState(Boolean(video.saved));const[followState,setFollowState]=useState<FollowState>(video.followingAuthor?'following':'none');const[reposted,setReposted]=useState(Boolean(video.reposted));const[pinned,setPinned]=useState(Boolean(video.pinned));const[commentsOpen,setCommentsOpen]=useState(false);const[reportOpen,setReportOpen]=useState(false);const[menuOpen,setMenuOpen]=useState(false);const[status,setStatus]=useState('');const[removed,setRemoved]=useState(false);const[deleting,setDeleting]=useState(false)
  const own=video.userId===user?.uid
  useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&entry.intersectionRatio>.7){void el.play().catch(()=>undefined);void recordView(video.id)}else el.pause()},{threshold:[.1,.7,.95]});observer.observe(el);return()=>observer.disconnect()},[video.id])
  const doLike=async()=>{const p=liked;setLiked(!p);try{setLiked(await toggleVideoLike(video.id,p))}catch(e){setLiked(p);setStatus(e instanceof Error?e.message:'Falha ao curtir.')}}
  const doSave=async()=>{const p=saved;setSaved(!p);try{setSaved(await toggleVideoBookmark(video.id,p))}catch(e){setSaved(p);setStatus(e instanceof Error?e.message:'Falha ao salvar.')}}
  const doFollow=async()=>{const p=followState;try{setFollowState(await toggleFollowState(video.userId,p))}catch(e){setFollowState(p);setStatus(e instanceof Error?e.message:'Falha ao seguir.')}}
  const doRepost=async()=>{const p=reposted;setReposted(!p);try{setReposted(await toggleRepost('video',video.id,p))}catch(e){setReposted(p);setStatus(e instanceof Error?e.message:'Falha ao repostar.')}}
  const doPin=async()=>{try{const next=await toggleProfilePin('video',video.id);setPinned(next);setMenuOpen(false);setStatus(next?'Clip fixado no perfil.':'Clip desafixado.');window.dispatchEvent(new Event('threadly:refresh'))}catch(e){setStatus(e instanceof Error?e.message:'Falha ao fixar Clip.')}}
  const share=async()=>{const url=`${location.origin}${location.pathname}#/watch/${video.id}`;if(navigator.share)await navigator.share({title:video.title,text:video.description,url}).catch(()=>undefined);else await navigator.clipboard.writeText(url).then(()=>setStatus('Link copiado.')).catch(()=>undefined)}
  const remove=async()=>{if(!own||deleting)return;if(!window.confirm('Excluir este Clip permanentemente? Curtidas, comentários, visualizações e mídia vinculada também serão removidos.'))return;setDeleting(true);setStatus('Excluindo Clip…');try{await deleteVideo(video.id);setRemoved(true);window.dispatchEvent(new Event('threadly:refresh'))}catch(e){setStatus(e instanceof Error?e.message:'Não foi possível excluir o Clip.')}finally{setDeleting(false);setMenuOpen(false)}}
  const followLabel=followState==='following'?'Seguindo':followState==='requested'?'Solicitado':'Seguir'
  if(removed)return null
  return <article className={`video-card ${pinned?'profile-pinned':''}`}><video ref={ref} src={video.videoUrl} muted={muted} loop playsInline preload="metadata" poster={video.thumbnailUrl??undefined} onClick={()=>ref.current?.paused?void ref.current.play():ref.current?.pause()}/><div className="video-scrim"/><button className="video-sound" onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><div className="video-meta"><div className="video-author"><button className="avatar-button" onClick={()=>navigate(`/u/${video.username}`)}><Avatar name={video.displayName} src={video.avatarUrl} size="sm"/></button><button className="author-copy" onClick={()=>navigate(`/u/${video.username}`)}><strong>{video.displayName}{pinned&&<span className="pin-badge"><Pin size={10}/> Fixado</span>}</strong><span>@{video.username}{video.collaboratorIds?.length?' · Collab':''}</span></button>{!own&&<button className={followState!=='none'?'following':''} onClick={()=>void doFollow()}>{followLabel}</button>}</div><button className="video-title-link" onClick={()=>navigate(`/watch/${video.id}`)}><h2>{video.title}</h2><p>{video.description}</p></button>{video.locationName&&<small className="video-location">{video.locationName}</small>}{status&&<small className="video-status">{status}</small>}</div><div className="video-actions"><button className={liked?'liked':''} onClick={()=>void doLike()}><span><Heart size={23} fill={liked?'currentColor':'none'}/></span><small>{formatCompact(video.likes+(liked&&!video.liked?1:0))}</small></button><button onClick={()=>setCommentsOpen(true)} disabled={video.commentsEnabled===false}><span><MessageCircle size={23}/></span><small>{formatCompact(video.comments)}</small></button><button className={reposted?'reposted':''} onClick={()=>void doRepost()}><span><Repeat2 size={22}/></span><small>Repost</small></button><button onClick={()=>void share()}><span><Share2 size={22}/></span><small>Enviar</small></button><button className={saved?'saved':''} onClick={()=>void doSave()}><span><Bookmark size={21} fill={saved?'currentColor':'none'}/></span><small>Salvar</small></button><div className="menu-wrap"><button onClick={()=>setMenuOpen(v=>!v)}><span><MoreHorizontal size={22}/></span></button>{menuOpen&&<div className="video-mini-menu">{own&&<button onClick={()=>void doPin()}><Pin size={15}/> {pinned?'Desafixar do perfil':'Fixar no perfil'}</button>}{own?<button className="danger-action" disabled={deleting} onClick={()=>void remove()}><Trash2 size={15}/> {deleting?'Excluindo…':'Excluir Clip'}</button>:<button onClick={()=>{setReportOpen(true);setMenuOpen(false)}}><Flag size={15}/> Denunciar</button>}</div>}</div></div><CommentsDialog videoId={video.id} open={commentsOpen&&video.commentsEnabled!==false} onClose={()=>setCommentsOpen(false)} canModerate={own}/><ReportDialog open={reportOpen} onClose={()=>setReportOpen(false)} targetType="video" targetId={video.id}/></article>
}
