alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.threads enable row level security;
alter table public.video_comments enable row level security;
alter table public.thread_replies enable row level security;
alter table public.video_likes enable row level security;
alter table public.thread_likes enable row level security;
alter table public.bookmarks enable row level security;
alter table public.thread_bookmarks enable row level security;
alter table public.follows enable row level security;
alter table public.video_views enable row level security;
alter table public.notifications enable row level security;
alter table public.reports enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

create or replace function public.is_conversation_member(p_conversation_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists (select 1 from public.conversation_members cm where cm.conversation_id=p_conversation_id and cm.user_id=(select auth.jwt()->>'sub'));
$$;

drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles for select to anon, authenticated using (true);
drop policy if exists "videos public read" on public.videos;
create policy "videos public read" on public.videos for select to anon, authenticated using (true);
drop policy if exists "threads public read" on public.threads;
create policy "threads public read" on public.threads for select to anon, authenticated using (true);
drop policy if exists "comments public read" on public.video_comments;
create policy "comments public read" on public.video_comments for select to anon, authenticated using (true);
drop policy if exists "thread replies public read" on public.thread_replies;
create policy "thread replies public read" on public.thread_replies for select to anon, authenticated using (true);
drop policy if exists "follows public read" on public.follows;
create policy "follows public read" on public.follows for select to anon, authenticated using (true);

drop policy if exists "profiles owner insert" on public.profiles;
create policy "profiles owner insert" on public.profiles for insert to authenticated with check ((select auth.jwt()->>'sub')=id);
drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update" on public.profiles for update to authenticated using ((select auth.jwt()->>'sub')=id) with check ((select auth.jwt()->>'sub')=id);

drop policy if exists "videos owner insert" on public.videos;
create policy "videos owner insert" on public.videos for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "videos owner update" on public.videos;
create policy "videos owner update" on public.videos for update to authenticated using ((select auth.jwt()->>'sub')=user_id) with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "videos owner delete" on public.videos;
create policy "videos owner delete" on public.videos for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "threads owner insert" on public.threads;
create policy "threads owner insert" on public.threads for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "threads owner update" on public.threads;
create policy "threads owner update" on public.threads for update to authenticated using ((select auth.jwt()->>'sub')=user_id) with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "threads owner delete" on public.threads;
create policy "threads owner delete" on public.threads for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "comments owner insert" on public.video_comments;
create policy "comments owner insert" on public.video_comments for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "comments owner delete" on public.video_comments;
create policy "comments owner delete" on public.video_comments for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread replies owner insert" on public.thread_replies;
create policy "thread replies owner insert" on public.thread_replies for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread replies owner delete" on public.thread_replies;
create policy "thread replies owner delete" on public.thread_replies for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);

drop policy if exists "video likes owner select" on public.video_likes;
create policy "video likes owner select" on public.video_likes for select to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "video likes owner insert" on public.video_likes;
create policy "video likes owner insert" on public.video_likes for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "video likes owner delete" on public.video_likes;
create policy "video likes owner delete" on public.video_likes for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread likes owner select" on public.thread_likes;
create policy "thread likes owner select" on public.thread_likes for select to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread likes owner insert" on public.thread_likes;
create policy "thread likes owner insert" on public.thread_likes for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread likes owner delete" on public.thread_likes;
create policy "thread likes owner delete" on public.thread_likes for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "bookmarks owner all read" on public.bookmarks;
create policy "bookmarks owner all read" on public.bookmarks for select to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "bookmarks owner insert" on public.bookmarks;
create policy "bookmarks owner insert" on public.bookmarks for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "bookmarks owner delete" on public.bookmarks;
create policy "bookmarks owner delete" on public.bookmarks for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread bookmarks owner read" on public.thread_bookmarks;
create policy "thread bookmarks owner read" on public.thread_bookmarks for select to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread bookmarks owner insert" on public.thread_bookmarks;
create policy "thread bookmarks owner insert" on public.thread_bookmarks for insert to authenticated with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "thread bookmarks owner delete" on public.thread_bookmarks;
create policy "thread bookmarks owner delete" on public.thread_bookmarks for delete to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "follows owner insert" on public.follows;
create policy "follows owner insert" on public.follows for insert to authenticated with check ((select auth.jwt()->>'sub')=follower_id);
drop policy if exists "follows owner delete" on public.follows;
create policy "follows owner delete" on public.follows for delete to authenticated using ((select auth.jwt()->>'sub')=follower_id);

drop policy if exists "views owner read" on public.video_views;
create policy "views owner read" on public.video_views for select to authenticated using ((select auth.jwt()->>'sub')=viewer_id);
drop policy if exists "notifications owner read" on public.notifications;
create policy "notifications owner read" on public.notifications for select to authenticated using ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "notifications owner update" on public.notifications;
create policy "notifications owner update" on public.notifications for update to authenticated using ((select auth.jwt()->>'sub')=user_id) with check ((select auth.jwt()->>'sub')=user_id);
drop policy if exists "reports owner insert" on public.reports;
create policy "reports owner insert" on public.reports for insert to authenticated with check ((select auth.jwt()->>'sub')=reporter_id);

drop policy if exists "conversations member read" on public.conversations;
create policy "conversations member read" on public.conversations for select to authenticated using (public.is_conversation_member(id));
drop policy if exists "members conversation read" on public.conversation_members;
create policy "members conversation read" on public.conversation_members for select to authenticated using (public.is_conversation_member(conversation_id));
drop policy if exists "members own update" on public.conversation_members;
create policy "members own update" on public.conversation_members for update to authenticated using (user_id=(select auth.jwt()->>'sub')) with check (user_id=(select auth.jwt()->>'sub'));
drop policy if exists "messages member read" on public.messages;
create policy "messages member read" on public.messages for select to authenticated using (public.is_conversation_member(conversation_id));
drop policy if exists "messages member insert" on public.messages;
create policy "messages member insert" on public.messages for insert to authenticated with check (sender_id=(select auth.jwt()->>'sub') and public.is_conversation_member(conversation_id));
